//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.Core.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Promotion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Promotion()
        {
            this.SalaryHistories = new HashSet<SalaryHistory>();
        }
    
        public int PromotionID { get; set; }
        public Nullable<int> EmpID { get; set; }
        public string Promotion_type { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<System.DateTime> Active_date { get; set; }
        public Nullable<System.DateTime> promotion_active { get; set; }
        public Nullable<decimal> Basics { get; set; }
        public Nullable<decimal> House_Rent { get; set; }
        public Nullable<decimal> Medical { get; set; }
        public Nullable<decimal> Convences { get; set; }
        public Nullable<decimal> Taxes { get; set; }
        public Nullable<decimal> Gross_Salary { get; set; }
    
        public virtual Employee Employee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SalaryHistory> SalaryHistories { get; set; }
    }
}
