//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.ViewModel
{
    using System;
    using System.Collections.Generic;
    
    public  class PromotionViewModel
    {
        public PromotionViewModel()
        {
            this.SalaryHistories = new HashSet<SalaryHistoryViewModel>();
        }
    
        public int PromotionID { get; set; }
        public Nullable<int> EmpID { get; set; }
        public string Promotion_type { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<System.DateTime> Active_date { get; set; }
        public Nullable<System.DateTime> promotion_active { get; set; }
        public Nullable<decimal> Basics { get; set; }
        public Nullable<decimal> House_Rent { get; set; }
        public Nullable<decimal> Medical { get; set; }
        public Nullable<decimal> Convences { get; set; }
        public Nullable<decimal> Taxes { get; set; }
        public Nullable<decimal> Gross_Salary { get; set; }
    
        public virtual EmployeeViewModel Employee { get; set; }
        public virtual ICollection<SalaryHistoryViewModel> SalaryHistories { get; set; }
    }
}
